== B. Good quality title

=== To which WMCP element(s) does it apply?

/gmd:MD_Metadata/gmd:identificationInfo//gmd:citation//gmd:title

=== What is being measured?
* field is not empty . Not evaluated by the tool because it his already being verified with the schema validation.
* title is following WMCP guidance. Not evaluated by the tool. Define it in the guidance.
* length is not too short or too long. (e.g. at least more than 3 words minimum and less than 150 characters).
* words are following Title case 

=== Why should we measure it?
Title is the first reference to a resource displayed and is helps with initial identification. 
If it's not available, too short, or too long then it makes it difficult for users understand the resource. 

=== How is the measurement executed?
Programmatically
Manually

=== What is (are) considered valid results?

* Length is between 3 words and 150 printable characters (numbers and letters).

* Acronyms:
  ** No only one acronym.
  ** No more than 3 acronyms per title.

=== WIS Guidance to be referenced here:

link:http://wis.wmo.int/file=3291[WMCP Guidance]

The Product Title and the Product Abstract are the two most relevant elements in the WCMP metadata
record, in the context of the WIS Product catalogues, as those two elements are presented to the users in
the search results and product description page. They therefore need to focus on highlighting the
product's key characteristics, to assist users searching for relevant products.
The title should be as specific about the product as is possible. If the product only contains one parameter,
for instance, this can be stated in the title; however, if the product contains many parameters, then a more general term should be used in the title, and the parameters stated elsewhere in the metadata
record (the abstract and/or the keywords). For a satellite product offering one main data parameter, the
title will typically define which parameter is contained in the product, and from which instrument or
instrument type it originates. For instance “AMSR-2 Sea Surface Temperature” or “SLSTR L1B radiances
and brightness temperatures”. 

Below is an example:
....
<gmd:identificationInfo>
 <gmd:MD_DataIdentification>
 <gmd:citation>
 <gmd:CI_Citation>
 <gmd:title>
 <gco:CharacterString>AMSR-2 Sea Surface Temperature</gco:CharacterString>
 </gmd:title>
 <gmd:alternateTitle>
 <gco:CharacterString>
 AMSR-2 Sea Surface Temperature SST
 </gco:CharacterString>
 </gmd:alternateTitle>
 . . . . . .
 </gmd:CI_Citation>
</gmd:citation>
 . . .. .
 </gmd:MD_DataIdentification>
</gmd:identificationInfo>
....

==== Title for GTS bulletins

The title for a GTS bulletin should also aim to be specific about the product, describing, as much as
possible, the type of observation, and including the bulletin code or identifier, and original distributor (e.g.
"from XXX").
For instance:
....
<gmd:identificationInfo>
 <gmd:MD_DataIdentification>
 <gmd:citation>
 <gmd:CI_Citation>
 <gmd:title>
 <gco:CharacterString>Sea level observations data [ SZPS01 ] for the South Pacific area</gco:CharacterString>
 </gmd:title>
....

=== Enforcing some of the defined guidance rules

Detect all template generated titles like IEDX02 BUFR bulletin available from EUMP (EUMETSAT - DARMSTADT).
A script can be created to detect that kind of information and it could be regularly generated.




