== B. Good Quality Title

=== To which WMCP element(s) does it apply?
/gmd:MD_Metadata/gmd:identificationInfo//gmd:citation//gmd:title

=== What is being measured?
The title field shall always be populated and and follow the principles of WMCP guidance. The length shall not be too short or too long. (e.g. at least more than 3 words minimum and less than 150 characters), represented in title case and has less than 3 acronyms. 

=== Why should we measure it?
Title is the first element of metadata information displayed and helps with initial identification. Meaningful and relevant information makes it easier for users to understand the resource. 
=== Rules for implementation ?

WHEN
title is missing ⇒  0 
Invalid examples: <gmd:title/>,  <gmd:title><gmd:title/>  and <gmd:title gco:nilReason="missing"/> 


IF
title has more 3 words or more ⇒ +1

IF
title has 150 characters or less ⇒ +1

IF
title only has printable characters (numbers and letters) ⇒ +1

IF
words in title are represented in title case ⇒ +1

IF 
title contains less than 3 acronyms ⇒ +1

Total possible score: 5

=== Score values

Low: Title exists, but doesn't pass any of the other requirements.

Medium: Score is 1 -3 

High: Score is 4 - 5

=== Guidance to score well on this assessment

The Product Title and the Product Abstract are the two most relevant elements in the WCMP metadata record, in the context of the WIS Product catalogues, as those two elements are presented to the users in the search results and product description page. They therefore need to focus on highlighting the product’s key characteristics, to assist users searching for relevant products. The title should be as specific about the product as is possible. If the product only contains one parameter, for instance, this can be stated in the title; however, if the product contains many parameters, then a more general term should be used in the title, and the parameters stated elsewhere in the metadata record (the abstract and/or the keywords). For a satellite product offering one main data parameter, the title will typically define which parameter is contained in the product, and from which instrument or instrument type it originates. For instance “AMSR-2 Sea Surface Temperature” or “SLSTR L1B radiances and brightness temperatures”. ~ WMCP Guidance



